Repository ArifurRahmanShezan/web-technologies-project, pull requests merged in 2025-02, with the labels that each got.

#6 employee functionally added
  employee/control/ajax_update.php
  employee/control/regcontrol.php
  employee/css/mystyle.css
  employee/js/myjs.js
  employee/model/db.php
  employee/view/dashboard.php
  employee/view/emp.php
  employee/view/logout.php
  view/login.php
Labels: enhancement

#7 employee bug fixed
  employee/control/connect.php
  employee/view/dashboard.php
Labels: bug

#8 serach features & bug fix
  sellerpage/control/editUser_control.php
  sellerpage/control/search_ad.php
  sellerpage/control/showuser_control.php
  sellerpage/css/showuser.css
  sellerpage/js/myjs.js
  sellerpage/model/db.php
  sellerpage/product/13.jpg
  sellerpage/view/all_ads.php
  sellerpage/view/edituser.php
  sellerpage/view/post_ad.php
  sellerpage/view/profile.php
  sellerpage/view/showusers.php
  sellerpage/view/viewad.php
Labels: bug, enhancement
